version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "1337:3000"
  #   links:
  #   - backend
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8000:8000"
  #   # links:
  #   # - db
  #   # depends_on:
  #   # db:
  #   #   condition: service_healthy
  # db:
  #   image: mysql:5.7
  #   ports:
  #     - "3309:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: hnr24
  #     MYSQL_USER: hnr24user
  #     MYSQL_PASSWORD: password
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "--password=password", "--user=hnr24user", "status"]
  #     interval: 15s
  #     timeout: 10s
  #     retries: 10